### PR TITLE
Add built-in sqrt

### PR DESCRIPTION
**Pull request by mbtools**
Not sure if this covers everything

### CODE REVIEW

**Comment by larshp** [comment]
looks good 👍 

let me know if you need it somewhere, then I'll do a release now, if not it might be some days

**Comment by mbtools** [comment]
needed to calc distance from center in https://exercism.org/tracks/abap/exercises/darts

**Comment by larshp** [comment]
ok, I'll publish a version later today, or might be tomorrow

**Comment by larshp** [comment]
1.8.13 published

**Comment by larshp** [comment]
I'll update the runner too

**Pull request merged**
