### PR TITLE
fix for interface static atributes regex flag error

### PR DESCRIPTION
**Pull request by Milosz1234517**

### CODE REVIEW

**Comment by Zeatynis** [comment]
https://github.com/abaplint/transpiler/issues/1142

**Review by larshp — CHANGES_REQUESTED** [review]
please add a unit test for this

in https://github.com/abaplint/transpiler/blob/main/test/code_structure/class.ts

**Review by larshp — APPROVED** [review]

**Comment by larshp** [comment]
thanks, it will be published as part of next release

**Comment by Zeatynis** [comment]
> thanks, it will be published as part of next release

Do you have a estimation for the release date?

**Comment by larshp** [comment]
typically there is releases every week, see https://github.com/abaplint/transpiler/commits/main

**Comment by Zeatynis** [comment]
Could you please make an exception? This bug is stopping us from merging pull request in our repo where we use transpiler.
Or is there any way to use that "experimental code" in the CI?

**Comment by larshp** [comment]
need at least https://github.com/abaplint/abaplint/pull/2935 published first, so it can be included in  https://github.com/abaplint/transpiler/pull/1175, which both have 2x ~15min regression tests

**Comment by larshp** [comment]
2.5.72 published

**Pull request merged**
