### PR TITLE
Restructuring tests

### PR DESCRIPTION
**Pull request by joltdx**

### CODE REVIEW

**Comment by joltdx** [comment]
I started making some kind of structure for the test in running_examples.ts. What do you think of of it? Should be pretty easy to find the right place, but is it too much? Maintainable over time?

**Comment by larshp** [comment]
replace the spaces " " in filenames with underscore "_"?

**Comment by joltdx** [comment]
Yes. Got it. You good with splitting in files per specific statement, expression, etc? There will be many files, but i think for unit tests it's probably still straight forward and easy to find where to put new tests...?

**Comment by larshp** [comment]
yea, its okay

**Comment by joltdx** [comment]
This is good to merge if you want/need to, otherwise I'll continue some more in this same branch tomorrow morning...

**Comment by larshp** [comment]
merging

**Pull request merged**
