### PR TITLE
nmin for integers

### PR DESCRIPTION
**Pull request by joltdx**

### CODE REVIEW

**Comment by larshp** [comment]
just push another commit to make the regression part run again

**Comment by joltdx** [comment]
There you go. Why red on master though, why was that affected?
Anyway nmin and nmax should return a type depending on the types of the inputs, this is not the case in this implementation. Only returns integer now...

**Comment by larshp** [comment]
master, I messed it up earlier, should be okay when this PR is merged

**Comment by larshp** [comment]
thanks 👍

**Pull request merged**
