### PR TITLE
LOOP supporting multiple conditions

### PR DESCRIPTION
**Pull request by joltdx**

### CODE REVIEW

**Comment by joltdx** [comment]
All checks failed, huh... 👎 What the... I'll check on this later...

**Comment by larshp** [comment]
feel free to add multiple test cases, its easier to debug small examples

syntax error,
image

**Comment by larshp** [comment]
fixed, can it be merged?

**Comment by joltdx** [comment]
Thanks. I see, I tried to fix the merge conflicts in github in the browser, trying to be quick. Failed. :)

**Comment by joltdx** [comment]
Yes, let's merge this one. It feels kindof like a workaroundish solution, but hey, it works! 👍

**Comment by larshp** [comment]
well, everything works until its broken 😁

**Pull request merged**
